server:
  port: 8383
  servlet:
    encoding:
      charset: UTF-8

spring:
  output:
    ansi:
      enabled: always

  cache:
    type: redis
    # Redis
    redis:
      pool:
        max-active: 10  #pool이 바닥났을 때 예외 발생 전, 커넥션 할당 차단 최대 시간(단위 밀리세컨드, 음수는 무제한 차단)
        max-idle: 10 #풀에서 관리하는 idle 커넥션의 최소수 대상 (양수일 때만 유효)
        min-idle: 2 # pool에 할당될 수 있는 커넥션 최대수 (음수로 하면 무제한)
      host: localhost
      port: 6379
      #password:
      time-to-live: 3600 # 데이터 유지 시간(sec)
      cache-null-values: true # null 캐싱 여부
    # Session
    session:
      store-type: redis
      redis:
        flush-mode: on_save

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/project_domain?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: kt0520
    sql-script-encoding: UTF-8 #한글깨짐


  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect  #JPA가 사용할 database의 dialect 설정
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        jdbc:
          time_zone: Asia/Seoul
        hibernate:
        "[format_sql]": true            #SQL을 보기 좋게 출력
        "[user_sql_comments]": true     #SQL생성 시 주석 포함
        "[highlight_sql]": true         #SQL에 색깔
        "[hbm2ddl.auto]": update  #update
        #"[implicit_naming_strategy]": "org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy" -> 기본값으로 설정되어 있어서 따로 설정하지 않아도 무방함
    open-in-view: false
    show-sql: true
    generate-ddl: true


jwt:
  secret: testtesttesttesttesttesttesttest

logging:
  config: classpath:log4j2.yml
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG

